local modpath = core.get_modpath(core.get_current_modname())

dofile(modpath .. "/block_world_nature_dirt.lua")
dofile(modpath .. "/block_world_nature_rock.lua")
dofile(modpath .. "/block_world_nature_grass.lua")
dofile(modpath .. "/block_world_nature_sand.lua")
dofile(modpath .. "/block_world_nature_snow.lua")
dofile(modpath .. "/block_world_nature_gravel.lua")
dofile(modpath .. "/block_world_nature_flint.lua")
dofile(modpath .. "/block_world_nature_leafs.lua")
dofile(modpath .. "/block_world_nature_wood.lua")
dofile(modpath .. "/block_world_nature_mossy_stone.lua")
dofile(modpath .. "/block_world_nature_placement.lua")
-- dofile(modpath .. "/flower_world_nature_poppy.lua")
dofile(modpath .. "/plant_world_nature_grass_0.lua")
dofile(modpath .. "/plant_world_nature_grass_1.lua")
dofile(modpath .. "/plant_world_nature_grass_2.lua")
dofile(modpath .. "/plant_world_nature_grass_3.lua")
dofile(modpath .. "/plant_world_nature_grass_4.lua")
dofile(modpath .. "/plant_world_nature_grass_5.lua")
dofile(modpath .. "/plant_world_nature_grass_6.lua")
dofile(modpath .. "/plant_world_nature_grass_7.lua")
dofile(modpath .. "/plant_world_nature_grass_8.lua")
dofile(modpath .. "/plant_world_nature_grass_9.lua")
dofile(modpath .. "/plant_world_nature_grass_10.lua")
core.register_alias("mapgen_stone", "everwild:rock")