local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath .. "/biome_river_land.lua")
dofile(modpath .. "/biome_post_river.lua")
dofile(modpath .. "/biome_before_mountains.lua")
dofile(modpath .. "/biome_gravel_flats.lua")
dofile(modpath .. "/biome_mountains.lua")
dofile(modpath .. "/biome_mountains_snow.lua")
dofile(modpath .. "/biome_underground.lua")
dofile(modpath .. "/biome_river.lua")
dofile(modpath .. "/biome_desert.lua")